application: bang-numbers
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: bang-numbers-favicon.png
  upload: bang-numbers-favicon\.png

- url: /bang-numbers/(.*)\.manifest
  static_files: bang-numbers/\1.manifest
  upload: bang-numbers/(.*)\.manifest
  mime_type: text/cache-manifest

- url: /bang-numbers
  static_dir: bang-numbers

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
